# TCL File Generated by Component Editor 8.1
# Wed Jan 28 09:27:35 JST 2009
# DO NOT MODIFY


# +-----------------------------------
# | 
# | pre_fifo_vip_empty_adapter "pre_fifo_vip_empty_adapter" v1.0
# | null 2009.01.28.09:27:35
# | 
# | 
# | C:/hhagiwar/VideoExample/NEEK_VIP_demo_v2_vga_lcd_bicubic_fb_sc/ip/my_pre_fifo_vip_empty_adapter/pre_fifo_vip_empty_adapter.v
# | 
# |    ./pre_fifo_vip_empty_adapter.v syn, sim
# | 
# +-----------------------------------


# +-----------------------------------
# | module pre_fifo_vip_empty_adapter
# | 
set_module_property NAME pre_fifo_vip_empty_adapter
set_module_property VERSION 1.0
set_module_property GROUP my_vip
set_module_property DISPLAY_NAME pre_fifo_vip_empty_adapter
set_module_property TOP_LEVEL_HDL_FILE pre_fifo_vip_empty_adapter.v
set_module_property TOP_LEVEL_HDL_MODULE pre_fifo_vip_empty_adapter
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file pre_fifo_vip_empty_adapter.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset clock end
set_interface_property clock_reset ptfSchematicName ""

add_interface_port clock_reset clock clk Input 1
add_interface_port clock_reset reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_streaming_sink
# | 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 1
set_interface_property avalon_streaming_sink symbolsPerBeat 3

set_interface_property avalon_streaming_sink ASSOCIATED_CLOCK clock_reset

add_interface_port avalon_streaming_sink din_ready ready Output 1
add_interface_port avalon_streaming_sink din_valid valid Input 1
add_interface_port avalon_streaming_sink din_data data Input 24
add_interface_port avalon_streaming_sink din_sop startofpacket Input 1
add_interface_port avalon_streaming_sink din_eop endofpacket Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_streaming_source
# | 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source dataBitsPerSymbol 8
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 1
set_interface_property avalon_streaming_source symbolsPerBeat 3

set_interface_property avalon_streaming_source ASSOCIATED_CLOCK clock_reset

add_interface_port avalon_streaming_source dout_ready ready Input 1
add_interface_port avalon_streaming_source dout_valid valid Output 1
add_interface_port avalon_streaming_source dout_data data Output 24
add_interface_port avalon_streaming_source dout_sop startofpacket Output 1
add_interface_port avalon_streaming_source dout_eop endofpacket Output 1
add_interface_port avalon_streaming_source dout_empty empty Output 2
# | 
# +-----------------------------------
