	DE10_Standard_Qsys u0 (
		.alt_vip_cl_cvi_0_clocked_video_vid_clk            (<connected-to-alt_vip_cl_cvi_0_clocked_video_vid_clk>),            //      alt_vip_cl_cvi_0_clocked_video.vid_clk
		.alt_vip_cl_cvi_0_clocked_video_vid_data           (<connected-to-alt_vip_cl_cvi_0_clocked_video_vid_data>),           //                                    .vid_data
		.alt_vip_cl_cvi_0_clocked_video_vid_de             (<connected-to-alt_vip_cl_cvi_0_clocked_video_vid_de>),             //                                    .vid_de
		.alt_vip_cl_cvi_0_clocked_video_vid_datavalid      (<connected-to-alt_vip_cl_cvi_0_clocked_video_vid_datavalid>),      //                                    .vid_datavalid
		.alt_vip_cl_cvi_0_clocked_video_vid_locked         (<connected-to-alt_vip_cl_cvi_0_clocked_video_vid_locked>),         //                                    .vid_locked
		.alt_vip_cl_cvi_0_clocked_video_vid_f              (<connected-to-alt_vip_cl_cvi_0_clocked_video_vid_f>),              //                                    .vid_f
		.alt_vip_cl_cvi_0_clocked_video_vid_v_sync         (<connected-to-alt_vip_cl_cvi_0_clocked_video_vid_v_sync>),         //                                    .vid_v_sync
		.alt_vip_cl_cvi_0_clocked_video_vid_h_sync         (<connected-to-alt_vip_cl_cvi_0_clocked_video_vid_h_sync>),         //                                    .vid_h_sync
		.alt_vip_cl_cvi_0_clocked_video_vid_color_encoding (<connected-to-alt_vip_cl_cvi_0_clocked_video_vid_color_encoding>), //                                    .vid_color_encoding
		.alt_vip_cl_cvi_0_clocked_video_vid_bit_width      (<connected-to-alt_vip_cl_cvi_0_clocked_video_vid_bit_width>),      //                                    .vid_bit_width
		.alt_vip_cl_cvi_0_clocked_video_sof                (<connected-to-alt_vip_cl_cvi_0_clocked_video_sof>),                //                                    .sof
		.alt_vip_cl_cvi_0_clocked_video_sof_locked         (<connected-to-alt_vip_cl_cvi_0_clocked_video_sof_locked>),         //                                    .sof_locked
		.alt_vip_cl_cvi_0_clocked_video_refclk_div         (<connected-to-alt_vip_cl_cvi_0_clocked_video_refclk_div>),         //                                    .refclk_div
		.alt_vip_cl_cvi_0_clocked_video_clipping           (<connected-to-alt_vip_cl_cvi_0_clocked_video_clipping>),           //                                    .clipping
		.alt_vip_cl_cvi_0_clocked_video_padding            (<connected-to-alt_vip_cl_cvi_0_clocked_video_padding>),            //                                    .padding
		.alt_vip_cl_cvi_0_clocked_video_overflow           (<connected-to-alt_vip_cl_cvi_0_clocked_video_overflow>),           //                                    .overflow
		.alt_vip_itc_mtlc_clocked_video_vid_clk            (<connected-to-alt_vip_itc_mtlc_clocked_video_vid_clk>),            //      alt_vip_itc_mtlc_clocked_video.vid_clk
		.alt_vip_itc_mtlc_clocked_video_vid_data           (<connected-to-alt_vip_itc_mtlc_clocked_video_vid_data>),           //                                    .vid_data
		.alt_vip_itc_mtlc_clocked_video_underflow          (<connected-to-alt_vip_itc_mtlc_clocked_video_underflow>),          //                                    .underflow
		.alt_vip_itc_mtlc_clocked_video_vid_datavalid      (<connected-to-alt_vip_itc_mtlc_clocked_video_vid_datavalid>),      //                                    .vid_datavalid
		.alt_vip_itc_mtlc_clocked_video_vid_v_sync         (<connected-to-alt_vip_itc_mtlc_clocked_video_vid_v_sync>),         //                                    .vid_v_sync
		.alt_vip_itc_mtlc_clocked_video_vid_h_sync         (<connected-to-alt_vip_itc_mtlc_clocked_video_vid_h_sync>),         //                                    .vid_h_sync
		.alt_vip_itc_mtlc_clocked_video_vid_f              (<connected-to-alt_vip_itc_mtlc_clocked_video_vid_f>),              //                                    .vid_f
		.alt_vip_itc_mtlc_clocked_video_vid_h              (<connected-to-alt_vip_itc_mtlc_clocked_video_vid_h>),              //                                    .vid_h
		.alt_vip_itc_mtlc_clocked_video_vid_v              (<connected-to-alt_vip_itc_mtlc_clocked_video_vid_v>),              //                                    .vid_v
		.audio_avalon_controller_conduit_end_CLK           (<connected-to-audio_avalon_controller_conduit_end_CLK>),           // audio_avalon_controller_conduit_end.CLK
		.audio_avalon_controller_conduit_end_LRCIN         (<connected-to-audio_avalon_controller_conduit_end_LRCIN>),         //                                    .LRCIN
		.audio_avalon_controller_conduit_end_DIN           (<connected-to-audio_avalon_controller_conduit_end_DIN>),           //                                    .DIN
		.audio_avalon_controller_conduit_end_LRCOUT        (<connected-to-audio_avalon_controller_conduit_end_LRCOUT>),        //                                    .LRCOUT
		.audio_avalon_controller_conduit_end_DOUT          (<connected-to-audio_avalon_controller_conduit_end_DOUT>),          //                                    .DOUT
		.audio_avalon_controller_conduit_end_BCLK          (<connected-to-audio_avalon_controller_conduit_end_BCLK>),          //                                    .BCLK
		.av_i2c_clk_pio_external_connection_export         (<connected-to-av_i2c_clk_pio_external_connection_export>),         //  av_i2c_clk_pio_external_connection.export
		.av_i2c_data_pio_external_connection_export        (<connected-to-av_i2c_data_pio_external_connection_export>),        // av_i2c_data_pio_external_connection.export
		.button_pio_external_connection_export             (<connected-to-button_pio_external_connection_export>),             //      button_pio_external_connection.export
		.clk_clk                                           (<connected-to-clk_clk>),                                           //                                 clk.clk
		.clk_mtlc_clk                                      (<connected-to-clk_mtlc_clk>),                                      //                            clk_mtlc.clk
		.clk_sdram_clk                                     (<connected-to-clk_sdram_clk>),                                     //                           clk_sdram.clk
		.clk_sys_clk                                       (<connected-to-clk_sys_clk>),                                       //                             clk_sys.clk
		.led_pio_external_connection_export                (<connected-to-led_pio_external_connection_export>),                //         led_pio_external_connection.export
		.pll_0_locked_export                               (<connected-to-pll_0_locked_export>),                               //                        pll_0_locked.export
		.reset_reset_n                                     (<connected-to-reset_reset_n>),                                     //                               reset.reset_n
		.sdram_wire_addr                                   (<connected-to-sdram_wire_addr>),                                   //                          sdram_wire.addr
		.sdram_wire_ba                                     (<connected-to-sdram_wire_ba>),                                     //                                    .ba
		.sdram_wire_cas_n                                  (<connected-to-sdram_wire_cas_n>),                                  //                                    .cas_n
		.sdram_wire_cke                                    (<connected-to-sdram_wire_cke>),                                    //                                    .cke
		.sdram_wire_cs_n                                   (<connected-to-sdram_wire_cs_n>),                                   //                                    .cs_n
		.sdram_wire_dq                                     (<connected-to-sdram_wire_dq>),                                     //                                    .dq
		.sdram_wire_dqm                                    (<connected-to-sdram_wire_dqm>),                                    //                                    .dqm
		.sdram_wire_ras_n                                  (<connected-to-sdram_wire_ras_n>),                                  //                                    .ras_n
		.sdram_wire_we_n                                   (<connected-to-sdram_wire_we_n>),                                   //                                    .we_n
		.td_reset_pio_external_connection_export           (<connected-to-td_reset_pio_external_connection_export>),           //    td_reset_pio_external_connection.export
		.touch_i2c_opencores_export_scl_pad_io             (<connected-to-touch_i2c_opencores_export_scl_pad_io>),             //          touch_i2c_opencores_export.scl_pad_io
		.touch_i2c_opencores_export_sda_pad_io             (<connected-to-touch_i2c_opencores_export_sda_pad_io>),             //                                    .sda_pad_io
		.touch_int_n_external_connection_export            (<connected-to-touch_int_n_external_connection_export>)             //     touch_int_n_external_connection.export
	);

